- name: Add Ollama Helm repository
  command: helm repo add ollama-helm https://otwld.github.io/ollama-helm/
  
- name: Update Helm repositories
  command: helm repo update
  
- name: Install Ollama chart
  command: helm install ollama ollama-helm/ollama --namespace ollama