---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-example
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ceph-storage
  csi:
    driver: rbd.csi.ceph.com
    volumeHandle: pv-example
    volumeAttributes:
      clusterID: 677da947-52bd-4a8b-aff0-3664ccef8382
      pool: CephPool
      imageFeatures: layering
