- name: Add Helm repo for Portainer
  ansible.builtin.command:
    cmd: helm repo add portainer https://portainer.github.io/k8s/
  register: add_repo_result
  retries: 3
  delay: 30
  until: add_repo_result.rc == 0
  changed_when: false
  become: true
  become_user: "{{ ansible_user }}"
  when: inventory_hostname == groups['masters'][0]


- name: Update Helm repos
  ansible.builtin.command:
    cmd: helm repo update
  register: update_repo_result
  retries: 3
  delay: 30
  until: update_repo_result.rc == 0
  changed_when: false
  become: true
  become_user: "{{ ansible_user }}"
  when: inventory_hostname == groups['masters'][0]


- name: Create portainer namespace
  ansible.builtin.command:
    cmd: kubectl create namespace portainer
  register: create_ns_result
  retries: 3
  delay: 10
  until: create_ns_result.rc == 0
  changed_when: create_ns_result.rc == 0
  become: true
  become_user: "{{ ansible_user }}"
  ignore_errors: true
  when: inventory_hostname == groups['masters'][0]

- name: Install Portainer if not present (using Helm)
  ansible.builtin.command:
    cmd: helm install portainer --namespace portainer stable/portainer
  register: helm_install_result
  retries: 3
  delay: 30
  until: helm_install_result.rc == 0
  changed_when: helm_install_result.rc == 0
  become: true
  become_user: "{{ ansible_user }}"
  when: inventory_hostname == groups['masters'][0]

