- name: Install Kubernetes Python library
  ansible.builtin.pip:
    name: kubernetes
    state: present
  become: true

- name: Create StorageClass for local storage
  kubernetes.core.k8s:
    state: present
    definition: |
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: local-storage
      provisioner: kubernetes.io/no-provisioner
      volumeBindingMode: WaitForFirstConsumer

- name: Patch local-storage StorageClass to be default
  ansible.builtin.shell: |
    kubectl patch storageclass local-storage -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
  become: true
  changed_when: false

- name: Add Portainer Helm repository
  kubernetes.core.helm_repository:
    name: portainer
    repo_url: https://portainer.github.io/k8s/
    state: present

- name: Update Helm repositories
  kubernetes.core.helm_repository:
    name: portainer
    state: updated

- name: Install or upgrade Portainer using Helm
  kubernetes.core.helm:
    name: portainer
    chart_ref: portainer/portainer
    namespace: portainer
    create_namespace: yes
    state: present
    set:
      - name: service.type
        value: LoadBalancer

- name: Apply Portainer LoadBalancer manifest
  kubernetes.core.k8s:
    state: present
    namespace: portainer
    src: https://downloads.portainer.io/ce2-19/portainer-lb.yaml
