- name: Add Helm repo for Portainer
  command: helm repo add portainer https://portainer.github.io/k8s/

- name: Update Helm repos
  command: helm repo update

- name: Install Portainer
  command: >
    helm install portainer portainer/portainer
    --namespace portainer
    --create-namespace
    --set service.type=NodePort
    --set service.nodePort=30777
