- name: Add Helm repo for Portainer
  ansible.builtin.command:
    cmd: helm repo add portainer https://portainer.github.io/k8s/
  register: add_repo_result
  retries: 3
  delay: 30
  until: add_repo_result.rc == 0
  changed_when: false
  become: true
  become_user: "{{ ansible_user }}"
  when: inventory_hostname == groups['masters'][0]

- name: Update Helm repos
  ansible.builtin.command:
    cmd: helm repo update
  register: update_repo_result
  retries: 3
  delay: 30
  until: update_repo_result.rc == 0
  changed_when: false
  become: true
  become_user: "{{ ansible_user }}"
  when: inventory_hostname == groups['masters'][0]

- name: Check if portainer namespace exists
  ansible.builtin.command:
    cmd: kubectl get namespace portainer
  register: check_namespace
  ignore_errors: true
  changed_when: false
  become: true
  become_user: "{{ ansible_user }}"
  when: inventory_hostname == groups['masters'][0]

- name: Create portainer namespace
  ansible.builtin.command:
    cmd: kubectl create namespace portainer
  when: 
    - check_namespace.rc != 0
    - inventory_hostname == groups['masters'][0]
  become: true
  become_user: "{{ ansible_user }}"
  ignore_errors: true

- name: Check if Portainer is already installed
  ansible.builtin.command:
    cmd: helm status portainer --namespace portainer
  register: portainer_check
  ignore_errors: true
  changed_when: false
  become: true
  become_user: "{{ ansible_user }}"
  when: inventory_hostname == groups['masters'][0]

- name: Install Portainer if not present (using Helm)
  ansible.builtin.command:
    cmd: helm install portainer --namespace portainer portainer/portainer
  register: helm_install_result
  retries: 3
  delay: 30
  until: helm_install_result.rc == 0
  changed_when: helm_install_result.rc == 0
  become: true
  become_user: "{{ ansible_user }}"
  when: 
    - inventory_hostname == groups['masters'][0]
    - portainer_check.rc != 0
