- name: Prepare monitoring
  hosts: masters
  gather_facts: true
  roles:
    - prepare-monitoring
- name: Install Portainer on Kubernetes
  hosts: masters
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - portainer