- name: Prepare monitoring
  hosts: masters
  gather_facts: true
  roles:
    - prepare-monitoring

- name: Deploy Portainer
  hosts: masters
  gather_facts: true
  roles:
    - portainer    

- name: Deploy Ollama
  hosts: masters
  gather_facts: true
  roles:
    - ollama

   
