#- name: Prepare monitoring
#  hosts: masters
#  gather_facts: true
#  roles:
#    - prepare-monitoring
#
#- name: Deploy Ollama
#  hosts: masters
#  gather_facts: true
#  roles:
#    - ollama
#

- name: Deploy Portainer
  hosts: main-node
  gather_facts: true
  roles:
    - portainer