# bootstraps first server and copies configs for others/agents
- name: Update Proxmox
  hosts: nodes
  gather_facts: true 
  roles:
    - prepare-infra

# creates directories for download and then downloads RKE2 and changes permissions
- name: Create VM template
  hosts: main-node
  gather_facts: true
  roles:
    - create_VM_template

# Creates RKE2 bootstrap manifests folder and copies kube-vip template over (configured with variables)
- name: Create VMs
  hosts: main-node
  gather_facts: false
  roles:
    - create_VMs