# bootstraps first server and copies configs for others/agents
- name: Prepare all nodes
  hosts: masters,workers
  gather_facts: true
  roles:
    - prepare-nodes

# creates directories for download and then downloads RKE2 and changes permissions
- name: Download RKE2
  hosts: masters,workers
  gather_facts: true
  roles:
    - rke2-download

# Creates RKE2 bootstrap manifests folder and copies kube-vip template over (configured with variables)
- name: Deploy Kube VIP
  hosts: masters
  gather_facts: true
  roles:
    - kube-vip

# bootstraps the first server, copies configs to nodes, saves token to use later
- name: Prepare RKE2 on Servers and Agents
  hosts: masters,workers
  gather_facts: true
  roles:
    - rke2-prepare

# Adds additional masters using the token from the previous task
- name: Add additional RKE2 Servers
  hosts: masters
  gather_facts: true
  roles:
    - add-server

# Adds workers to the cluster
- name: Add additional RKE2 Agents
  hosts: workers
  gather_facts: true
  roles:
    - add-agent

# Finish kube-vip, add metallb
- name: Apply manifests after cluster is created
  hosts: masters
  gather_facts: true
  roles:
    - apply-manifests