- name: Clone VMs from Template
  proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    api_host: "{{ groups['main-node'][0] }}" 
    node: "{{ groups['main-node'][0] }}" 
    full: true
    name: "{{ item.name }}"
    newid: "{{ item.vmid }}"
    state: present
    clone: "{{ proxmox_clone_template }}"
    storage: "{{ proxmox_storage }}"
    timeout: 100
  loop: "{{ vms }}"

- name: Migrate VMs to nodes
  proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    api_host: "{{ groups['main-node'][0] }}"
    node: "{{ item.node }}"  
    vmid: "{{ item.vmid }}"
    state: stopped 
    timeout: 60
    migrate: true
  loop: "{{ vms }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.node != groups['main-node'][0] 


- name: VMs IP change and cores
  proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    api_host: "{{ groups['main-node'][0] }}"
    node: "{{ item.node }}"
    vmid: "{{ item.vmid }}"
    ipconfig:
      ipconfig0: "ip={{ item.ipv4_address }},gw={{ item.ipv4_gateway }}"
    nameservers: 1.1.1.1
    cores: "{{ item.cores }}"
    update: true
    state: present
    timeout: 15
  loop: "{{ vms }}"
  loop_control:
    label: "{{ item.name }}"

- name: Start VMs after migration
  proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    api_host: "{{ groups['main-node'][0] }}"
    node: "{{ item.node }}"
    vmid: "{{ item.vmid }}"
    state: started
    timeout: 600
  loop: "{{ vms }}"
  loop_control:
    label: "{{ item.name }}"
  register: update_result

- name: Waiting to start virtual server machine completely
  wait_for:
    timeout: 200
  when: update_result.changed
