- name: Update apt package index
  apt:
    update_cache: yes

- name: Install python3-kubernetes
  apt:
    name: python3-kubernetes
    state: present

- name: Debug Info
  debug:
    msg: "python3-kubernetes is installed successfully"
    
- name: Create Persistent Volume
  k8s:
    state: present
    definition: "{{ lookup('template', '../pv.yaml') }}"
  register: pv_result

- name: Debug Persistent Volume Creation Result
  debug:
    var: pv_result

- name: Create Persistent Volume Claim
  k8s:
    state: present
    definition: "{{ lookup('template', '../pvc.yaml') }}"
  register: pvc_result

- name: Debug Persistent Volume Claim Creation Result
  debug:
    var: pvc_result
