name: Connect to HomeLab

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'

jobs:
  connect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install ansible-lint
  
      - name: Run Ansible Lint
        run: ansible-lint -r .
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Requests
        run: pip install requests

      - name: Install proxmoxer
        run: pip install proxmoxer
        
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          tags: tag:ci
    
      - name: Create Proxmox infrastructure
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/infrastructure.yml
          directory: ./
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          requirements: ansible/collections/requirements.yaml
          options: |
            --inventory ansible/inventory/.ansible_inventory
            --extra-vars "@ansible/inventory/variables.yml"
            --extra-vars "proxmox_api_user=${{ secrets.PROXMOX_API_USER }}" 
            --extra-vars "proxmox_api_token_id=${{ secrets.PROXMOX_API_TOKEN_ID }}" 
            --extra-vars "proxmox_api_token_secret=${{ secrets.PROXMOX_API_TOKEN_SECRET }}"
            --verbose

      - name: Run Kubernetes install
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/install_kubernetes.yml
          directory: ./
          # Use secrets manager to access SSH key securely
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          requirements: ansible/collections/requirements.yaml
          # Use the copied inventory file #ansible/inv.yml
          options: |
           --inventory ansible/inventory/.ansible_inventory 
           --extra-vars "@ansible/inventory/variables.yml"
           --verbose

      - name: Deployment
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/deployment.yml
          directory: ./
          # Use secrets manager to access SSH key securely
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          requirements: ansible/collections/requirements.yaml
          # Use the copied inventory file #ansible/inv.yml
          options: |
           --inventory ansible/inventory/.ansible_inventory 
           --extra-vars "@ansible/inventory/variables.yml"
           --verbose